development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      uri: <%= Rails.application.credentials.mongo_uri %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: nemtr_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= Rails.application.credentials.mongo_uri %>
      options:
        skip_version_check: true
        safe: true
